// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsknUc7M_V7dbeXbZpCzjJK4S5hPQd954',
    appId: '1:941286930069:web:cdb74ab53e5db23f43cd9c',
    messagingSenderId: '941286930069',
    projectId: 'calbnb-71137',
    authDomain: 'calbnb-71137.firebaseapp.com',
    databaseURL: 'https://calbnb-71137-default-rtdb.firebaseio.com',
    storageBucket: 'calbnb-71137.firebasestorage.app',
    measurementId: 'G-1X7FCPE1RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD79YfgF2ru5Mqne5w5Gq9z2JINt0ORd_E',
    appId: '1:941286930069:android:8b082501c4a61eb943cd9c',
    messagingSenderId: '941286930069',
    projectId: 'calbnb-71137',
    databaseURL: 'https://calbnb-71137-default-rtdb.firebaseio.com',
    storageBucket: 'calbnb-71137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4UNHKffFOTtxZviWzaO9rO8QKP1lFDSs',
    appId: '1:941286930069:ios:1ef87642155f5e0343cd9c',
    messagingSenderId: '941286930069',
    projectId: 'calbnb-71137',
    databaseURL: 'https://calbnb-71137-default-rtdb.firebaseio.com',
    storageBucket: 'calbnb-71137.firebasestorage.app',
    iosClientId: '941286930069-k85cl5qtql6ecf2bnc6dcae14gfjsafa.apps.googleusercontent.com',
    iosBundleId: 'com.calbnb.app.calbnb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4UNHKffFOTtxZviWzaO9rO8QKP1lFDSs',
    appId: '1:941286930069:ios:1ef87642155f5e0343cd9c',
    messagingSenderId: '941286930069',
    projectId: 'calbnb-71137',
    databaseURL: 'https://calbnb-71137-default-rtdb.firebaseio.com',
    storageBucket: 'calbnb-71137.firebasestorage.app',
    iosClientId: '941286930069-k85cl5qtql6ecf2bnc6dcae14gfjsafa.apps.googleusercontent.com',
    iosBundleId: 'com.calbnb.app.calbnb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsknUc7M_V7dbeXbZpCzjJK4S5hPQd954',
    appId: '1:941286930069:web:2c9ef0312091251f43cd9c',
    messagingSenderId: '941286930069',
    projectId: 'calbnb-71137',
    authDomain: 'calbnb-71137.firebaseapp.com',
    databaseURL: 'https://calbnb-71137-default-rtdb.firebaseio.com',
    storageBucket: 'calbnb-71137.firebasestorage.app',
    measurementId: 'G-MQZ50E6YTW',
  );
}
